// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkI19bzQH4UwDaF0OrPs1UTXxFYH6SuY',
    appId: '1:883794554833:web:f6883d5c8338678d793af0',
    messagingSenderId: '883794554833',
    projectId: 'act13-userauth',
    authDomain: 'act13-userauth.firebaseapp.com',
    storageBucket: 'act13-userauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCONjfgUnAGfM3YAFb-Tlh_vBPNKGr8Yk4',
    appId: '1:883794554833:android:0d80cc4560c9c114793af0',
    messagingSenderId: '883794554833',
    projectId: 'act13-userauth',
    storageBucket: 'act13-userauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYw8OJtMvG-HqolUJ7ohsKAlBwNr5TK4',
    appId: '1:883794554833:ios:d838dbf11f24a5a5793af0',
    messagingSenderId: '883794554833',
    projectId: 'act13-userauth',
    storageBucket: 'act13-userauth.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYw8OJtMvG-HqolUJ7ohsKAlBwNr5TK4',
    appId: '1:883794554833:ios:d838dbf11f24a5a5793af0',
    messagingSenderId: '883794554833',
    projectId: 'act13-userauth',
    storageBucket: 'act13-userauth.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfkI19bzQH4UwDaF0OrPs1UTXxFYH6SuY',
    appId: '1:883794554833:web:3e19ac9fa9c86612793af0',
    messagingSenderId: '883794554833',
    projectId: 'act13-userauth',
    authDomain: 'act13-userauth.firebaseapp.com',
    storageBucket: 'act13-userauth.firebasestorage.app',
  );
}
